### ISSUE TITLE
Extra full name is not styled

### ISSUE THREAD

**Issue by binhtran432k** [LazyVim/lazyvim.github.io#128]
On my machine, all extra full name is not styled make it display on the same line with description (e.g. https://www.lazyvim.org/extras/coding/blink)
![Image](https://github.com/user-attachments/assets/9b8db34c-d71b-49ae-b88f-b14d8e3b3e97)

**Comment by folke** [comment]
Fixed. (site is rebuilding)
Thanks for letting me know.
