### ISSUE TITLE
Add a small tip on <leader> in Keymaps page

### ISSUE THREAD

**Issue by haochengxia** [LazyVim/lazyvim.github.io#21]
As a beginner, LazyVim has greatly improved my experience with Neovim. The default `<leader>` key in LazyVim is `<Space>`, rather than the backslash `\` mentioned in `:h mapleader`. I found this out by searching through the repository.

Although this may be common knowledge for some users, I believe it would be helpful to include a small tip in the [keymaps](https://www.lazyvim.org/keymaps) page for some new users.

**Comment by folke** [comment]
It's under the default options see here https://www.lazyvim.org/configuration/general#options

Using space as the leader is also very common. Most people use space
