### ISSUE TITLE
installation.md Docker instructions issue

### ISSUE THREAD

**Issue by jt4201** [LazyVim/lazyvim.github.io#44]
The docker instructions listed will fail with a 'platform unsupported' error when Mason tries to install stylua (and lua-language-server if you go that far). Alpine Linux is compiled with musl and the Mason install of stylua requires glibc (mason.nvim issue 1406).

Using archlinux as the Docker base image is another option. Downside for Mx macbook users is that there is no arm64 official archlinux image.

**Comment by folke** [comment]
Yes, that's a limitation of mason. The docker command is just to have a quick look at how LazyVim works.

You can always use another image if needed
