### ISSUE TITLE
UI tab improperly shows dressing.nvim 3 times

### ISSUE THREAD

**Issue by seofernando25** [LazyVim/lazyvim.github.io#54]
The first link seems correct, the two other ones return a 404.

[Here is the page](https://www.lazyvim.org/plugins/ui)

https://github.com/LazyVim/lazyvim.github.io/blob/b9214b1995a61b431bcae986e7b92494f2d2d138/docs/plugins/ui.md?plain=1#L74-L161

![image](https://github.com/LazyVim/lazyvim.github.io/assets/26195439/c5c55d71-7702-4421-9836-26d0556a3c61)

Edit: Resolved by #50 but there is no open issue for it

**Comment by seofernando25** [comment]
Duplicate of #50 but there is no issue for it

**Comment by folke** [comment]
fixed
