### ISSUE TITLE
Example: convert lsp configuration from json to lua 

### ISSUE THREAD

**Issue by S1M0N38** [LazyVim/lazyvim.github.io#6]
LSP configurations are usually given in json format (a format compatible with vscode)
```json
{
  "texlab.rootDirectory": null,
  "texlab.build.executable": "tectonic",
  "texlab.build.args": ["-X", "compile", "%f"],
  "texlab.forwardSearch.executable": "/Applications/Skim.app/Contents/SharedSupport/displayline",
  "texlab.forwardSearch.args": ["-g", "%l", "%p", "%f"]
}
```
For Lua/Neovim novices (of whom I am one), converting from JSON to Lua is not always straightforward. For the above code, the version for lazy.nvim would be...
```lua
return {
  "neovim/nvim-lspconfig",
  opts = {
    -- LSP Server Settings
    ---@type lspconfig.options
    servers = {
      texlab = {  -- LSP server name
        settings = {
          texlab = { -- again LSP server name !
            rootDirectory = nil,
            build = {
              executable = "tectonic",
              args = { "-X", "compile", "%f"},
            },
            forwardSearch = {
              executable = "/Applications/Skim.app/Contents/SharedSupport/displayline",
              args = { "-g", "%l", "%p", "%f" },
            },
          },
        },
      },
    },
  },
}

```
Moreover, `:LspLog` does not provide useful information for debugging incorrect configurations as the erroneous configuration will not load, resulting in a silent bug.

I think that an example as I gave above could be added to the docs [here](https://www.lazyvim.org/plugins/lsp#nvim-lspconfig).

**Comment by folke** [comment]
You can always check what's being send to the lsp, with `:Neoconf lsp`
