### ISSUE TITLE
Feature request: Include news on LazyVim.org

### ISSUE THREAD

**Issue by gotgenes** [LazyVim/lazyvim.github.io#95]
I appreciate all the work that you have put into lazyvim.org. I have become accustomed to going there first when searching for documentation on LazyVim, which I think is the intent of all the effort. So from my perspective, it's been really effective!

I am wondering if you'd be willing to also include the [LazyVim news](https://github.com/LazyVim/LazyVim/blob/main/NEWS.md) on lazyvim.org. It's the one document I consistently have to traverse to GitHub to look at since it's only available there, or in Neovim on occasional updates to LazyVim the plugin.

**Comment by folke** [comment]
Fixed in https://github.com/LazyVim/lazyvim.github.io/commit/b5234480801773c1d195db0a3c5a9cf804c03cc5

Thank you for the suggestion!

**Comment by gotgenes** [comment]
Thank you for all you give to the Neovim community!
